-- USDA FoodData Central import (2026-04-30 release).
--
-- Adds `usda` as a food provider and the columns its data needs that Open Food
-- Facts never carried: a full micronutrient panel, label portions, the raw
-- ingredient statement, and derived-but-auditable allergen and health-claim
-- fields.
--
-- Two deliberate separations in here:
--   * `allergens_derived` is NOT `allergens`. USDA publishes no structured
--     allergen field, only an ingredient statement, so anything we extract is
--     inference. `allergens` stays reserved for source-declared data and the
--     existing exclusion filter stays trustworthy.
--   * `micronutrients` is jsonb keyed by nutrient slug rather than a 27M-row
--     join table. A food's panel is always read whole, never a column at a
--     time, so one row fetch beats a join; `nutrients` below carries the
--     labels, units and display order to render it.

ALTER TYPE "food_source" ADD VALUE IF NOT EXISTS 'usda';
--> statement-breakpoint

-- Which USDA tier a row came from. Drives trust and expected panel depth:
-- foundation/sr_legacy/survey_fndds carry 65-159 nutrients, branded ~14.
ALTER TABLE "foods" ADD COLUMN IF NOT EXISTS "usda_data_type" text;
--> statement-breakpoint
-- USDA's own category string, kept verbatim alongside our `group` vocabulary
-- so a mis-mapped group never destroys the original classification.
ALTER TABLE "foods" ADD COLUMN IF NOT EXISTS "usda_category" text;
--> statement-breakpoint
ALTER TABLE "foods" ADD COLUMN IF NOT EXISTS "barcode" text;
--> statement-breakpoint
ALTER TABLE "foods" ADD COLUMN IF NOT EXISTS "ingredients_text" text;
--> statement-breakpoint

-- FDA "big 9" allergens parsed out of `ingredients_text`. Inferred, never
-- authoritative --- see the note at the top.
ALTER TABLE "foods" ADD COLUMN IF NOT EXISTS "allergens_derived" text[] DEFAULT '{}' NOT NULL;
--> statement-breakpoint
-- How `allergens_derived` was produced, so a future parser change can
-- re-derive only the rows it owns. NULL where nothing was derived.
ALTER TABLE "foods" ADD COLUMN IF NOT EXISTS "allergen_source" text;
--> statement-breakpoint

-- Nutrient-content claims computed from the values by FDA rule, not written by
-- hand and not generated by a model.
ALTER TABLE "foods" ADD COLUMN IF NOT EXISTS "health_claims" text[] DEFAULT '{}' NOT NULL;
--> statement-breakpoint
ALTER TABLE "foods" ADD COLUMN IF NOT EXISTS "claims_basis" text;
--> statement-breakpoint

-- { "<nutrient slug>": <amount in that nutrient's unit> }, per 100 g/ml to
-- match `serving_size` on the same row. Slug carries the unit (iron_mg,
-- vitamin_d_ug) so a value is never read against the wrong scale.
ALTER TABLE "foods" ADD COLUMN IF NOT EXISTS "micronutrients" jsonb;
--> statement-breakpoint
ALTER TABLE "foods" ADD COLUMN IF NOT EXISTS "source_published_at" date;
--> statement-breakpoint

CREATE INDEX IF NOT EXISTS "foods_barcode_idx" ON "foods" ("barcode") WHERE "barcode" IS NOT NULL;
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "foods_usda_data_type_idx" ON "foods" ("usda_data_type");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "foods_allergens_derived_idx" ON "foods" USING gin ("allergens_derived");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "foods_health_claims_idx" ON "foods" USING gin ("health_claims");
--> statement-breakpoint
-- jsonb_path_ops: we ask "does this food contain nutrient X above Y", never
-- "what keys exist", and it builds a smaller index than the default opclass.
CREATE INDEX IF NOT EXISTS "foods_micronutrients_idx" ON "foods" USING gin ("micronutrients" jsonb_path_ops);
--> statement-breakpoint

-- The nutrient dictionary behind `foods.micronutrients`. `rank` is USDA's own
-- display order, which is what makes a rendered panel read like a Nutrition
-- Facts label instead of an alphabetical dump.
CREATE TABLE IF NOT EXISTS "nutrients" (
  "usda_id" integer PRIMARY KEY,
  "slug" text NOT NULL,
  "name" text NOT NULL,
  "unit" text NOT NULL,
  "rank" numeric(10, 1),
  -- FDA 2016 adult Daily Value in `unit`, NULL where the nutrient has none.
  -- Populated for the subset that drives health_claims.
  "daily_value" numeric(12, 4),
  "is_macro" boolean DEFAULT false NOT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "nutrients_slug_unique" ON "nutrients" ("slug");
--> statement-breakpoint

-- Household measures: "1 cup, chopped" -> 150 g. Without these a member can
-- only log in grams, which is not how anyone describes a portion.
CREATE TABLE IF NOT EXISTS "food_portions" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "food_id" uuid NOT NULL REFERENCES "foods"("id") ON DELETE CASCADE,
  "seq_num" integer DEFAULT 0 NOT NULL,
  "amount" numeric(10, 3),
  "unit" text,
  "description" text,
  "modifier" text,
  "gram_weight" numeric(10, 2) NOT NULL,
  -- True for the serving printed on the package, which is the one a member
  -- means by "one serving" and the basis every health claim is tested against.
  "is_label_serving" boolean DEFAULT false NOT NULL
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "food_portions_food_idx" ON "food_portions" ("food_id", "seq_num");
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "food_portions_unique" ON "food_portions" ("food_id", "seq_num", "gram_weight");
